image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - Static Analysis
  - Test
  - Deploy

flake8:
  stage: Static Analysis
  tags:
    - AR-GL-R-1
  script:
  - pip install flake8
  - flake8

test:
  stage: Test
  tags:
    - AR-GL-R-1
  script:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - pytest --cov=Flask_Cinema_Site/ Tests
    - coverage xml
    - coverage html
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - htmlcov/

pages:
  stage: Deploy
  tags:
    - AR-GL-R-1
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master